### ISSUE TITLE
Target Triple with OS version?

### ISSUE THREAD

**Issue by erikbdev** [kabiroberai/swift-sdk-darwin#5]
Hello,

Awesome project! I was wondering if its a good idea to include the SDK version in the triple's os?
```
arm64-apple-ios18.0
```

**Comment by kabiroberai** [comment]
Taking a step back, there are two important version numbers when building Darwin apps:

1. Deployment target: this is the oldest version of iOS that your app claims to support. Can often be a few years old (e.g. you may want to support devices on iOS 16.0 and up.)
2. SDK version: you usually want to use the latest SDK version (eg 18.2 right now) which gives you access to newer APIs.

e.g. if your deployment target is 16.0 and your SDK is 18.2, you'll be able to use the new iOS 18 APIs although you'll need to add a version check (`if #available(iOS 18, *)` for example) and provide a fallback for iOS 16-17.

Which of the two versions do you want to control? Conventionally, `arm64-apple-ios16.0` means "use whatever SDK I have, and set the deployment target to iOS 16.0." If this is your aim then SwiftPM actually has a nicer way to do this: just use the `platforms` argument in your Package.swift.

```swift
let package = Package(
  name: "my-package",
  platforms: [.iOS("16.0")],
  ...
)
```

If on the other hand you _do_ want to control the SDK version, could you elaborate on your use case?

**Comment by erikbdev** [comment]
I actually was thinking as a way to know what sdks were installed before removing/updating the `.artifactbundle`, but of course it is always recommended to use the latest Base SDK.

With this, I currently have no use case to specify Base SDK version within the target tuple, but if I do, I will open this issue again!
